<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<!-- Mude de net8.0 para net8.0-windows -->
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- Adiciona suporte ao Windows Forms -->
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.GenAI" Version="*" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" />
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.11" />
		<PackageReference Include="Spectre.Console" Version="0.57.2" />
		<PackageReference Include="SQLitePCLRaw.core" Version="3.0.5" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
		<PackageReference Include="System.Numerics.Tensors" Version="10.0.11" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
		<PackageReference Include="Terminal.Gui" Version="1.15.0" />
	</ItemGroup>

</Project>
